version: '3.3'
services:
 mongo:
   image: mongo
   ports:
     - "27017:27017"
   volumes:
     - './db:/data/db'
   environment:
    - MONGO_INITDB_ROOT_USERNAME=user
    - MONGO_INITDB_ROOT_PASSWORD=password
    - MONGO_INITDB_DATABASE=test
    - MONGO_NON_ROOT_USERNAME=app
    - MONGO_NON_ROOT_PASSWORD=password